spring:
  application:
    name: customer-service
  mongodb:
    username: mongo
    password: secret
    host: localhost
    port: 27017
    database: customer
    authentication-database: admin
#      uri: mongodb://mongo:secret@localhost:27017/customer?authSource=admin

server:
  port: 8090