spring:
  application:
    name: customer-service
  mongodb:
    username: mongo
    password: secret
    host: localhost
    port: 27017
    database: customer
    authentication-database: admin

springdoc:
  api-docs:
    path: /api/v1/customers/v3/api-docs

server:
  port: 8090